server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yogo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


